---
title: "workspace"
author: "Nathan Haas"
date: "9/30/2019"
output: html_document
---


```{r}
library(classdata)
happy <- readRDS("HAPPY.rds")
names(happy) = tolower(names(happy))

#Data Cleaning
happy[happy$polviews %in% "IAP"] <- "NA"
happy$polviews[happy$polviews %in% "DK"] <- "NA"
happy$health[happy$health %in% "IAP"] <- "NA"
happy$health[happy$health %in% "DK"] <- "NA"
happy$finrela[happy$finrela %in% "IAP"] <- "NA"
happy$finrela[happy$finrela %in% "DK"] <- "NA"

#casting each factor variable
happy$age[happy$age == "89 OR OLDER"] <- "89"
happy$happy = as.character(happy$happy)
happy$year = as.numeric(happy$year)
happy$age = as.numeric(happy$age)
happy$sex = as.character(happy$sex)
happy$marital = as.character(happy$marital)
happy$degree = as.character(happy$degree)
happy$finrela = as.character(happy$finrela)
happy$health = as.character(happy$health)
happy$wtssall = as.numeric(happy$wtssall)
happy$partyid = as.character(happy$partyid)
happy$polviews = as.character(happy$polviews)


#ordering the factors by age
library(tidyverse)
happyvsage = fct_reorder(happy$happy, happy$age, .fun=median, .desc = FALSE)
sexvsage = fct_reorder(happy$sex, happy$age, .fun=median, .desc = FALSE)
maritalvsage = fct_reorder(happy$marital, happy$age, .fun=median, .desc = FALSE)
degreevsage = fct_reorder(happy$degree, happy$age, .fun=median, .desc = FALSE)
finrelavsage = fct_reorder(happy$finrela, happy$age, .fun=median, .desc = FALSE)
healthvsage = fct_reorder(happy$health, happy$age, .fun=median, .desc = FALSE)
partyidvsage = fct_reorder(happy$partyid, happy$age, .fun=median, .desc = FALSE)
polviewsvsage = fct_reorder(happy$polviews, happy$age, .fun=median, .desc = FALSE)
```

Part 2
```{r}
library(ggplot2)

ggplot(happy, aes(year, fill = sex)) + geom_histogram(binwidth=2) + labs(title="Histogram of Age by Sex", x="Age", y="Count")

ggplot(happy, aes(degree, age)) + geom_boxplot() + labs(title = "Degree by Age")

ggplot(happy, aes(happy, fill=health)) + geom_bar(color="red", position="fill") + coord_flip() + 
labs(title = "Barchart of Happy regarding health", y="Percentage", x="happy")

ggplot(happy, aes(age, color=happy)) + geom_freqpoly(binwidth=1) + labs(title = "Happiness by Age", x="Age", y="Count")

ggplot(happy, aes(marital, fill=happy)) + geom_bar(position="fill") + labs(title = "Barchart of Happy regarding marital status", y="Percentage", x="happy")


```

